### ISSUE TITLE
feat: 슬랙 입금/출금 봇 구분하기

### ISSUE THREAD

**Issue by choshsh** [jesh-hub/account-book-slack#26]
### What is this issue? 🔍

- 슬랙 봇을 2개로 관리 (입금/출금)
- 봇 이름은 `@plus`, `@minus`

### 기타
- 금액 앞에 `-` 기호 붙이는게 너무 비효율적임

**Comment by choshsh** [comment]
이 작업은 안하기로 함

**Comment by j2e4** [comment]
> 이 작업은 안하기로 함

- 백엔드 소스 구조가 너무 많이 바뀌어야 한다고 한다.
- 관리해야 하는 슬랙 Bot이 총 세 개가 된다.
